// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    // AAvatar: typeof import('ant-design-vue/es')['Avatar']
    // ABadge: typeof import('ant-design-vue/es')['Badge']
    // ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    // ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    // AButton: typeof import('ant-design-vue/es')['Button']
    // ACard: typeof import('ant-design-vue/es')['Card']
    // ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    // ACol: typeof import('ant-design-vue/es')['Col']
    // ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    // ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    // ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    // AForm: typeof import('ant-design-vue/es')['Form']
    // AFormItem: typeof import('ant-design-vue/es')['FormItem']
    // AInput: typeof import('ant-design-vue/es')['Input']
    // ALayout: typeof import('ant-design-vue/es')['Layout']
    // ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    // ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    // ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    // AMenu: typeof import('ant-design-vue/es')['Menu']
    // AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    // AModal: typeof import('ant-design-vue/es')['Modal']['default']
    // AppProvider: typeof import('./../src/components/app-provider/AppProvider.vue')['default']
    // ARow: typeof import('ant-design-vue/es')['Row']
    // ASelect: typeof import('ant-design-vue/es')['Select']
    // ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    // ASpace: typeof import('ant-design-vue/es')['Space']
    // ATable: typeof import('ant-design-vue/es')['Table']
    // ATabPane: typeof import('ant-design-vue/es')['TabPane']
    // ATabs: typeof import('ant-design-vue/es')['Tabs']
    // ATag: typeof import('ant-design-vue/es')['Tag']
    // ATextarea: typeof import('ant-design-vue/es')['Textarea']
    // BaseDetail: typeof import('./../src/components/base-detail/BaseDetail.vue')['default']
    BaseIcon: typeof import('./../src/components/base-icon/BaseIcon.vue')['default']
    // BaseList: typeof import('./../src/components/base-list/BaseList.vue')['default']
    // BaseSearch: typeof import('./../src/components/base-search/BaseSearch.vue')['default']
    // DictSelect: typeof import('./../src/components/dict/DictSelect.vue')['default']
    // DictTag: typeof import('./../src/components/dict/DictTag.vue')['default']
    GoTo: typeof import('./../src/components/go-to/GoTo.vue')['default']
    // MyRender: typeof import('./../src/components/my-render/MyRender.vue')['default']
    // SvgIcon: typeof import('./../src/components/svg-icon/SvgIcon.vue')['default']
  }
}

export {}
